"""Output formatting."""
import json

from .model import RULES


def to_json(result: dict) -> str:
    return json.dumps(result, indent=2, sort_keys=False) + "\n"


def to_text(result: dict) -> str:
    head = "agentlint %s  root=%s  yaml=%s  files=%d" % (
        result["agentlint_version"], result["root"], result["yaml_parser"], len(result["files"]))
    scope = result.get("scope") or {}
    if scope.get("changed_since"):
        head += "  scope=changed-since %s" % scope["changed_since"]
    lines = [head]
    for f in result["findings"]:
        loc = f["file"] + (":%d" % f["line"] if f.get("line") else "")
        lines.append("%-5s %s %s %s" % (f["severity"].upper(), f["id"], loc, f["message"]))
        if f.get("suggestion"):
            lines.append("      fix: %s" % f["suggestion"])
    s = result["summary"]
    lines.append("errors: %d, warnings: %d, info: %d" % (s["error"], s["warning"], s["info"]))
    for nc in result["not_checked"]:
        lines.append("not checked: %s" % nc)
    return "\n".join(lines) + "\n"


def catalogue_markdown() -> str:
    """Markdown catalogue, grouped by family, generated from the registry (kept in sync by a test)."""
    families = [("GN", "General file hygiene"), ("AG", "Agent definitions"), ("SK", "Skill files"),
                ("IN", "Instructions and prompt files"), ("CF", "MCP, hooks, environment, manifests"),
                ("XF", "Cross-file")]
    out = ["# agentlint rule catalogue", "",
           "Generated by `agentlint.py --list-rules --format markdown`. Do not edit by hand.", ""]
    for fam, title in families:
        out += ["## %s — %s" % (fam, title), "", "| ID | Severity | Tag | Runtime | Check | Source |", "|---|---|---|---|---|---|"]
        for rid in sorted(r for r in RULES if r.startswith(fam)):
            r = RULES[rid]
            out.append("| %s | %s | %s | %s | %s | %s |" % (rid, r.severity, r.tag, r.runtime, r.title, r.source))
        out.append("")
    return "\n".join(out)


def catalogue_text() -> str:
    return "\n".join("%s  %-7s %-6s %-7s %s" % (rid, r.severity, r.tag, r.runtime, r.title)
                     for rid, r in sorted(RULES.items())) + "\n"
